<a href="https://colab.research.google.com/github/venturaedward/Linear-Algebra-58019/blob/main/PrelimExam_Ventura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Multiplication Table

In [25]:
import numpy as np
#multiplication table
num1 = ([1, 2, 3, ,4 5, 6, 7, 8, 9, 10])
num2 = ([1, 2, 3, ,4 5, 6, 7, 8, 9, 10])
times = num1 * num2
print(times)
#doubles all values
num = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
multiply = num * num
print(multiply)

SyntaxError: ignored

In [12]:
#Question 1
import numpy as np
#multiplication table
num1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
num2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
times = num1 * num2
print(times)


[  1   4   9  16  25  36  49  64  81 100]


In [13]:
#Question 2
import numpy as np
num = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
multiply = num * num
print(multiply)

[  1   4   9  16  25  36  49  64  81 100]


In [21]:
#Question 3
import numpy as np

ones = np.array([1,1,1,1])
diagonal = np.diag(ones)

print(diagonal)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
#Question 4

In [36]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
len =len([[1, 2, 3, 4],
          [5, 6, 7, 8],
          [9, 10, 11, 12]])

print(matrix)
print(len)

TypeError: ignored

In [40]:
#Question 5
import numpy as np
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

add = arrayOne + arrayTwo
print(add)

square = add * add
print(square)

[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]
