<a href="https://colab.research.google.com/github/venturaedward/Linear-Algebra-58019/blob/main/PythonExercise3_Ventura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector Addition

In [11]:
import numpy as np
A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])
A+B+C
np.add(A,np.add(B,C))
np.sum(B)

2

Vector Subtraction

In [13]:
import numpy as np
np.subtract(A,B)
A-B

array([-2,  1,  2])

Vector Multiplication

In [14]:
import numpy as np
np.multiply(A,B)
A*B

array([3, 2, 0])

Vector Division

In [15]:
import numpy as np
np.divide(A,B)
A/B
C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])
C//D
np.array(A/B,dtype=int)

array([0, 2, 0])